### ISSUE TITLE
minidlna - add patch to disable cover art resizing

### ISSUE THREAD

**Issue by zyxmon** [Entware/Entware-ng#325]
https://sourceforge.net/p/minidlna/patches/70/

**Comment by ZacWolf** [comment]
Looks like this has been superseeded by version 1.2
[https://sourceforge.net/projects/minidlna/files/minidlna/1.2.0/](https://sourceforge.net/projects/minidlna/files/minidlna/1.2.0/)

Any change someone could build this into an .ipk?

**Comment by ryzhovau** [comment]
We sync with [upstream](https://github.com/openwrt/packages/tree/master/multimedia) once per 1-2 months. New `minidlna` will arrive here if it will be updated there.
