### ISSUE TITLE
Package request: gammu (SMS gate)

### ISSUE THREAD

**Issue by argakon** [Entware/Entware-ng#385]
Would be nice to use this package with 3g modem, for remote reboot and other service things
[gammu package in openwrt](https://github.com/openwrt/packages/tree/master/utils/gammu)

Thanks.

**Comment by ryzhovau** [comment]
Did you tried `smstools3`?

**Comment by argakon** [comment]
On entware - no, but i tried smstools many years ago and got many problems with, for example, encoding. Gammu is much more powerful and easy to use(on raspberry pi gammu worked like a charm with only one line changed - modem serial device /dev/ttyUSB0 -> /dev/ttyUSB2). And gammu have integration with mysql.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
