### ISSUE TITLE
Request package: AtomicParsley

### ISSUE THREAD

**Issue by LegoChicken** [Entware/Entware-ng#391]
Could AtomicParsley (http://atomicparsley.sourceforge.net/) be added for MP4 tagging and other formats.  This would be useful for running get_iplayer (https://github.com/get-iplayer/get_iplayer and https://github.com/get-iplayer/get_iplayer/wiki/installation#external-programs). As far as I can see Perl is available and the perl modules could be installed. In an ideal world a package would be added for get-iplayer with all its dependencies including integration with a webserver to run its CGI interface (see https://github.com/get-iplayer/get_iplayer/blob/master/get_iplayer.cgi). This presumably needs putting in a separate package request.

**Comment by ryzhovau** [comment]
Abandoned 10+ years ago, not sure I want to add this, sorry.

**Comment by LegoChicken** [comment]
Is still under development in https://bitbucket.org/wez/atomicparsley. It still used by get-iplayer and the newer version is available (for example) in Ubuntu (https://launchpad.net/~jon-hedgerows/+archive/ubuntu/get-iplayer)

**Comment by ryzhovau** [comment]
> Is still under development in https://bitbucket.org/wez/atomicparsley. 

That's the new link, where AtomicParsley development continues. Seems Ok.

> This would be useful for running get_iplayer (https://github.com/get-iplayer/get_iplayer and https://github.com/get-iplayer/get_iplayer/wiki/installation#external-programs). As far as I can see Perl is available and the perl modules could be installed.

This is just a Perl script. Did you tried to run it on Entware environment? OpenWrt guys (our Perl upstream) scattered perl in quite weird manner into 100+ separate packages and I'm not sure I'm ready to catch up all `get_iplayer` dependencies. Please make sure it's running first, or AtomicParsley will be useless there.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
