### ISSUE TITLE
Package Request: jdupes

### ISSUE THREAD

**Issue by 51DD5** [Entware/Entware-ng#503]
Please add jdupes. Many users seem to be relying on fdupes for file de-duplication. By the sound of it fdupes development has ground to a halt and the baton has bee picked up by Jody Bruchon with the forked project jdupes: https://github.com/jbruchon/jdupes, which is also much faster, more efficient and more powerful than fdupes and would prove a useful tool. I personally would like to see it added to carry out de-duplication on my NAS where fdupes took a long time, then crashed at 50%!
Thanks ;-).

**Comment by wshyang** [comment]
Seconded, would really appreciate seeing this on entware-ng

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
