### ISSUE TITLE
Package Request: git-annex

### ISSUE THREAD

**Issue by jivank** [Entware/Entware-ng#507]
git-annex would be a wonderful addition for embedded devices, especially with external storage.

https://git-annex.branchable.com/

**Comment by rodoviario** [comment]
I was going to ask for the same. There is no reliable tutorial for installing a good cloud/sync solution. I used to use owncloud (in php5, before the split to nextcloud). Now I cannot install nextcloud and make it work in php7 / nginx. The other git-based cloud solution is sparkleshare, but it needs flatpack to run.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
