### ISSUE TITLE
request for several audio tools

### ISSUE THREAD

**Issue by satfreak** [Entware/Entware-ng#531]
I must say, please to see the followup for optware.
But i do mis some stuf, of witch i use for batch processing on my qnap.

I miss flac, vorbis tools,shntools and cuetools.
I know they havent been updated for some time, but stil i use those the handle serval thing with audio files.
Flac to check a musicfile is its corrupted or not, and metaflac to write tags and add coverart.
Vorbis tools to convert mp3 to ogg, and also to edit tags and add coverart.
cuetools and shntools to cute a musicfile with cuefile, to serval music files.

Would it be possible to add those to entware, so one can handle it through a bash script ?

Thanks would be very nice, if it would be included.

**Comment by brianbillman** [comment]
I second this.  Have a huge FLAC library on Synology and was disappointed to see flac not available.

**Comment by Mentia** [comment]
+1 same thing, I use getID3 to manage my flac files, but getID3 uses metaflac to write them, sitll not available on synology

**Comment by zyxmon** [comment]
@Mentia - if you can upgrade to Entware, I can upload flac package with flac & metaflac utilities.
Entware is a new project - the result of Entware-ng and Entware-3x merge.
What is your architecture?

**Comment by Mentia** [comment]
@zyxmon Synology DS 716+II so Intel Celeron N3160 architecture. Thx !!

**Comment by zyxmon** [comment]
>> Celeron N3160 architecture

This is not an architecture, this is CPU. My guess is - you use old Entware-ng that cannot be upgraded to the new Entware. You need to install new Entware (x64 architecture) to test new packages. The procedure is similar to Entware-ng but the installation scripts have different URL.
X64 is here - http://bin.entware.net/x64-k3.2/installer/generic.sh
Instructions will be available soon.

More installer links are here - http://forums.zyxmon.org/viewtopic.php?p=17841#p17841

**Comment by zyxmon** [comment]
flac, shntool, vorbis-tools, cuetools are waiting for testers.
To test packages Entware (not Entware-ng or Entware-3x) must be installed.
Please tell us your architecture. It should be one of
aarch64-k3.10,  armv5sf-k3.2,  armv7sf-k2.6,  armv7sf-k3.2,  mipselsf-k3.4,  mipssf-k3.4, x64-k3.2
sf means soft float
k3.2 means minimal kernel version 3.2 of the supported kernel

**Comment by Mentia** [comment]
Thx ! will try
Best

**Comment by satfreak** [comment]
If this means, that Entware has support for those tools and is x64 i'm willing to test it !

**Comment by zyxmon** [comment]
@satfreak - just install Entware (if you have qnap NAS there are 2 qpkg (standard and alternative) for installation).
I'll upload test x64 packages for you.

**Comment by zyxmon** [comment]
x64 test packages are here - http://bin.entware.net/x64-k3.2/test/
To install run `opkg install URL`

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge
