### ISSUE TITLE
Package Request: Arpon

### ISSUE THREAD

**Issue by swetoast** [Entware/Entware-ng#535]
Arpon would be a nice addition compared to arpwatch

http://arpon.sourceforge.net/documentation.html#9

**Comment by ryzhovau** [comment]
There's `arpwatch` in repo. What benefits will bring `arpon`? Is there any killer features?

**Comment by swetoast** [comment]
SARPI (Static ARP Inspection) for the statically configured networks without DHCP;
DARPI (Dynamic ARP Inspection) for the dynamically configured networks with DHCP;
HARPI (Hybrid ARP Inspection) for the statically and dynamically configured networks with DHCP.

**Comment by swetoast** [comment]
little more flexible then arpwatch thats why i figured its nice to have an alternative in the repo

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
