### ISSUE TITLE
Package request: mmv

### ISSUE THREAD

**Issue by cha-ka-lak** [Entware/Entware-ng#624]
mmv is "multiple move" and allows to mass move, copy or rename files.

Examples: 
https://wiki.ubuntuusers.de/mmv/

Source code is available with GPL:
https://packages.qa.debian.org/m/mmv.html

### Platform:
I would love to see this package for QNAP 64bit Intel.

**Comment by rico666** [comment]
As I am the submitter of the now closed duplicate #746 (sorry), I'd like to support that request.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
