### ISSUE TITLE
Package Request: lsyncd

### ISSUE THREAD

**Issue by htrex** [Entware/Entware-ng#625]
### Package: lsyncd

https://github.com/axkibe/lsyncd

For new package to be added:

---------------------------------------------------------------------
Make sure there's no similar package already added
---------------------------------------------------------------------
I couldn't find a similar package that uses our beloved, mature, universal, fast and reliable rsync command.

---------------------------------------------------------------------
Describe killer features of new package
---------------------------------------------------------------------
Lsyncd watches a local directory trees event monitor interface (inotify or fsevents). It aggregates and combines events for a few seconds and then spawns one (or more) process(es) to synchronize the changes. By default this is rsync. Lsyncd is thus a light-weight live mirror solution that is comparatively easy to install not requiring new filesystems or block devices and does not hamper local filesystem performance.

---------------------------------------------------------------------
Make sure it's open source and not abandoned (at least for last 5 years or so)
---------------------------------------------------------------------
GPL 2.0, started in 2009, last update Feb 2017, see https://github.com/axkibe/lsyncd/graphs/contributors 

### Platform:

---------------------------------------------------------------------
please, tell us what feed and\or devices are you using.
---------------------------------------------------------------------
Zyxel NAS326 FW 5.21

---------------------------------------------------------------------
Be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.
---------------------------------------------------------------------
I'm ready to help with testing.

Thanks

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
