### ISSUE TITLE
Package Request: ADCH++

### ISSUE THREAD

**Issue by dekysk** [Entware/Entware-ng#637]
### Package: ADCH++

Hi is there any possibility of adding ADCH++ to the package list?
http://adchpp.sourceforge.net/

Killer feature:  ADC protocol with Encryption via ADCS

### Platform:

Asus RT-N16/DD-WRT v3.0/Entware

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
