### ISSUE TITLE
Package request cdrtools: relates to #111 package request mkisofs

### ISSUE THREAD

**Issue by matjm** [Entware/Entware-ng#638]
### Package: cdrtools
I think there is a need for the cdrtools or genisoimage package so that mkisofs is available.
optware ipkg used to have cdrtools but this is not available with entware opkg
without these tools there is no clear way to create iso images from a folder of files on a nas, for example
dd may be available but creating an iso from a folder still requires mkisofs
also the other cdrtools are very useful for a range of things
in the previously closed issue #111 ryzhovau said there was no sense to add this
I would like to know why there is no need for this or the broader cdrtools package?
if there is an alternative way with entware packages to create an iso from a folder please let me know
otherwise please consider including the cdrtools or something similar like debian's genisoimage tools
i think cdrtools would be the prefered choice.
Thanks.
### Platform: cross, x86
qnap ts 853A

**Comment by ryzhovau** [comment]
No problem. This package was requested at least twice, so let it be.

**Comment by matjm** [comment]
Ok that's fine. I will leave it for now.
(Though I did not see another request aside from #111)
However, no-one has actually answered the question that was posed in #111 and which I have re-iterated above.
that is, why is cdrtools seen as not required within entware and why was #111 closed?
Is this still the prevailing view or is someone going to keep the issue open and look at providing the package at some stage? (If not, what's the alternative?)

**Comment by poe84it** [comment]
I think that especially on a QNap it's essential to have the ability to create an ISO from a folder!

**Comment by bartoszcisek** [comment]
Yep, t would be great to have cdrtools on Qnap :-)

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
