### ISSUE TITLE
Package request : ngrok/ngrok-c

### ISSUE THREAD

**Issue by noreplyme** [Entware/Entware-ng#651]
### Package: ngrok or ngrok-c

Exposing a local server behind a NAT or firewall to the internet.

Repo for ngrok: https://github.com/inconshreveable/ngrok
Repo for ngrok-c: https://github.com/dosgo/ngrok-c

### Platform: MIPS (Device: Xiaomi MI mini)

**Comment by ryzhovau** [comment]
> Exposing a local server behind a NAT or firewall to the internet.
What's killer feature of `ngrok` comparing to `pagekite`? Not sure I want to add another packages with the same purpose.

**Comment by noreplyme** [comment]
Actually didn't know about pagekite. Sure if we already have it, no need to add ngrok.
Thank you for info!

**Comment by noreplyme** [comment]
Killer feature of ngrok - it's free, and has unlimited bandwidth, custom ports etc.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
