### ISSUE TITLE
Package request: cgit

### ISSUE THREAD

**Issue by tgram75** [Entware/Entware-ng#659]
### Package: cgit

**Web site: https://git.zx2c4.com/cgit**

**Make sure there's no similar package already added:**
I don't believe there currently exists a package containing a web interface for git repositories.

**Describe killer features of new package:**
cgit is a super-fast, light-weight cgi interface for git repositories. It would allow for a nice web interface for VCS functionality exposed by the exisiting _git_ and _git-http_ packages.

**Make sure it's open source and not abandoned (at least for last 5 years or so):**
GPLv2

**Please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms:**
Cgit is written in C and is extremely lean.

### Platform:

**Please, tell us what feed and\or devices are you using:**
QNAP TS-253Pro, x64

**Be ready to check issue-related changes or it will be closed after 30 days with "no response" status:**
Yes. I will also be happy to perform package testing and provide feedback.

**Comment by tgram75** [comment]
I got package working for Enware-3X. Please see PR here: https://github.com/Entware-for-kernel-3x/entware-packages-3x/pull/2

**Comment by zyxmon** [comment]
@tgram75 - Entware-3x is now in RO mode. Please make your PR for cgit to Entware. Add cgit to rtndev repo - https://github.com/Entware/rtndev
