### ISSUE TITLE
New Package Request: git-lfs

### ISSUE THREAD

**Issue by rejeangroleau** [Entware/Entware-ng#670]
### Package: git-lfs

For new package to be added:
https://github.com/git-lfs/git-lfs

... for managing large files with Git (currently supported by github and bitbucket, nice to have when mirroring these repositories).

### Platform:

Architecture: armv7soft (asus wrt merlin, RT-AC87U)

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
