### ISSUE TITLE
Package Request Zabbix-Proxy

### ISSUE THREAD

**Issue by jonny190** [Entware/Entware-ng#676]
### Package: Zabbix-Proxy

For existing package:

 **** Enabled features ****
SNMP monitoring:        NO
IPMI monitoring:        NO
Web monitoring:         NO
VMware monitoring:      NO
ODBC:                   NO
SSH2 support:           NO
IPv6 support:          YES
TLS support:            NO

Can we get SNMP, WEB and SSH2 support
### Platform:

I'm using this on an Asus AC87U running Merlin firmware

**Comment by ryzhovau** [comment]
> Can we get SNMP, WEB and SSH2 support

Please, ask [upstream](https://github.com/openwrt/packages/tree/master/admin) for that.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
