### ISSUE TITLE
Package Request: GO compiler

### ISSUE THREAD

**Issue by steff123** [Entware/Entware-ng#688]
### Package: <go>

I'd like to ask for the compiler for the go programming language. 
Source code and instructions can be found [here](https://golang.org/dl/).

I'm using 
`Linux NAS001 3.4.6 #1 Fri Oct 3 16:06:36 CST 2014 armv5tel unknown`
(little endian)

Thanks

Regards
Steff

**Comment by southwolf** [comment]
You can just download it by your own. That's what I'm doing.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
