### ISSUE TITLE
Package Request: uWSGI

### ISSUE THREAD

**Issue by idlesign** [Entware/Entware-ng#692]
Hi, 

Thank you for the repo. 
Would be nice to see uWSGI in it.

### Package: uWSGI

uWSGI is a stack to implement application servers for various programming languages and protocols using a common api and a common configuration style. Versatility, performance, low-resource usage and reliability are the strengths of the project.

[uWSGI build system](http://uwsgi-docs.readthedocs.io/en/latest/BuildSystem.html)
[Supported languages and platforms](http://uwsgi-docs.readthedocs.io/en/latest/LanguagesAndPlatforms.html)
[Supported Platforms/Systems](http://uwsgi-docs.readthedocs.io/en/latest/SupportedPlatforms.html)

### Platform:

- Netgear WNR3500L v2 / Tomato Firmware 1.28.0000 MIPSR2-140 K26 USB AIO
- Python 3

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
