### ISSUE TITLE
Package request: miniupnpd 

### ISSUE THREAD

**Issue by atiensivu** [Entware/Entware-ng#694]
### Package: miniupnpd

For new package to be added:
Provides upnp better than default dd-wrt, actually has NAT-PMP.
The changes for the makefile are already there, just need a binary now.

### Platform:armv7l
Netgear R7000 running Entware-ng under Kong build from June 2017

**Comment by ZacWolf** [comment]
It's my understanding that minupnpd isn't intended to be used stand-alone, but as part of some of the already existing packages such as miniDNLA (Media Server) which is available in the repo. Maybe explain what you're hoping to accomplish with it "stand-alone"?

**Comment by atiensivu** [comment]
I'm pretty sure it can be used standalone. The main reason is to use it as a replacement for the iffy upnp server that comes by default with dd-wrt. I've played around with minidlna on dd-wrt, too, but am interested in the NAT-PMP support and configurability of miniupnpd 

Not a huge deal if it is a hassle to compile

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
