### ISSUE TITLE
Package Request: B.A.T.M.A.N. or OLSR

### ISSUE THREAD

**Issue by derd3000** [Entware/Entware-ng#696]
### Package: B.A.T.M.A.N. or OLSR

It would be really great if someone could add the package B.A.T.M.A.N or OLSR for the ARM Platform to create mesh networks with These routers.

There is already something here: https://github.com/Entware-ng/entware-routing but I don't know if it's usable?

**Comment by colindean** [comment]
I would like this, too, for @pittmesh / @metamesh. I searched around and cannot seem to find where the binaries produced from https://github.com/Entware-ng/entware-routing are hiding.

**Comment by colindean** [comment]
I'm confused and it's likely simply a result of me diving into OpenWRT/Entware/LEDE head first.

I see that entware-routing is enabled in `feeds.conf`: https://github.com/Entware-ng/Entware-ng/blob/master/feeds.conf#L2

It looks like [olsrd may just need to be enabled in the configs](https://github.com/Entware-ng/Entware-ng/blob/master/configs/mipselsf.config#L4260) for each architecture.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
