### ISSUE TITLE
Package request: certbot (Let's Encrypt Client)

### ISSUE THREAD

**Issue by specialkk** [Entware/Entware-ng#707]
### Package: `certbot`

This would be really nice for those of us doing small-scale hosting on our devices with HTTPS. Typically you have certbot attempt to renew certificates once a month (Let's Encrypt-issued SSL certificates expire after 3). I believe all of certbot's dependencies are already supported, it just needs a prebuilt package. [This page](https://certbot.eff.org/docs/packaging.html) might be helpful for creating it.

### Platform
- dd-wrt r32597 (arm7) on Netgear R6700 and Netgear AC1450

**Comment by ryzhovau** [comment]
I [tried](http://forums.zyxmon.org/viewtopic.php?t=5309) it before and I see no sense to pack it for several reasons:

* it's just a shell (ot Python script), there's nothing to compile here,
* it requires WWW server, which is not always trivial on embedded devices,
* Let's Encrypt/StartSSL/WoSign certs [becomes untrusted](https://groups.google.com/a/chromium.org/forum/#!topic/net-dev/FKXe-76GO8Y).

**Comment by RogueScholar** [comment]
Sorry to clutter the issue thread, @ryzhovau, but I wasn't able to find any mention of Let's Encrypt losing browser acceptance in the thread you linked, only StartSSL and WoSign. If you have reason to believe Let's Encrypt is also on its way out the door I'd dearly love any information you can share about it; I have a ton of  domains operating with their certificates.

As for adding certbot to entware, I think it's a reasonable request honestly. I understand there's nothing to compile but it's kind of a pain to bootstrap it with pip and it seems like something that would be handled more elegantly with opkg dependencies for the requisite Python modules.

It actually doesn't require a separate http server daemon either, there's a standalone mode that handles the validation challenges internally provided the user has the understanding of opening the necessary ports with iptables. (If command-line options for the iptables stuff could be cooked into an entware package for certbot that would _really_ be something.) I know Let's Encrypt and the whole ACME concept is a bit controversial in light of the phishing abuses its been subverted for, but I think that anytime a user find the motivation to learn to encrypt packet traffic its something to be nurtured.

Just my two cents.

**Comment by KamistixX** [comment]
Yes please add an easy way to use certbot on entware ! Let's Encrypt is getting more and more widespread, and a lot of improvements and new features are coming. 
See https://letsencrypt.org/upcoming-features/

**Comment by ryzhovau** [comment]
> Sorry to clutter the issue thread, @ryzhovau, but I wasn't able to find any mention of Let's Encrypt losing browser acceptance in the thread you linked, only StartSSL and WoSign. 

My bad. Let's Encrypt is still in game.

**Comment by KamistixX** [comment]
Thank you @ryzhovau for looking into this :)

**Comment by omega69** [comment]
Would be really perfect to have it

**Comment by norcino** [comment]
+1 I'm trying to find an alternative solution but so far, no success

**Comment by KamistixX** [comment]
@norcino I am currently using GetSSL script available here https://github.com/srvrco/getssl and it does the job perfectly. It can be run on any Linux machine, since it is simply a bash script.

**Comment by norcino** [comment]
@KamistixX Thank you very much, I'm going to try it tonight, I would like to use it in my DDWRT nas with nginx.

**Comment by norcino** [comment]
@KamistixX  fyi, it didn't work out of the box. I opened an [issue ](https://github.com/srvrco/getssl/issues/350) but I think the OS I use doesn't support it.
Thank you anyway

**Comment by ryzhovau** [comment]
@norcino, see the [first line](https://github.com/srvrco/getssl/blob/master/getssl#L1) of `getssl` script.

**Comment by norcino** [comment]
@ryzhovau thanks, so bash is not sh, I know very little about linux ad you might have understood. In my system, I think I font have bash so i need to find a way to install it. Cheers

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
