### ISSUE TITLE
Package request: wireshark/tshark

### ISSUE THREAD

**Issue by kolyshkin** [Entware/Entware-ng#712]
Wireshark (used to be known as Ethereal) is a tcpdump reborn -- with GUI, bells and whistles.
tshark is its command-line equivalent of tcpdump (with more features). tshark was (still is) available from optware, so it was a surprise for me it's not in entware-ng.

### Platform:

> tell us what feed and\or devices are you using.

ASUS RT-68U with Tomato by Shibby, ASUS RT-68U with Merlin.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
