### ISSUE TITLE
Package request :  libio-socket-ssl-perl

### ISSUE THREAD

**Issue by matw100** [Entware/Entware-ng#722]
Package : libio-socket-ssl-perl

Used on a Zyxel 540 NAS;

Logitech Media Server Version: 7.7.4 - 1415167000 @ Wed Nov 5 08:13:46 UTC 2014
Hostname: Lounge-NAS2
Server IP Address: x.x.x.x
Server HTTP Port Number: 9000
Operating system: Linux - EN - utf8
Platform Architecture: unknown
Perl Version: 5.20.1 - arm-linux

Logitech have removed support for the Spotify plugin however there has been a new one written, this however requires libio-socket-ssl-perl to be installed.

Link to the Spotty 1.1.0 page

http://forums.slimdevices.com/showthread.php?107615-Announce-Spotty-v1-1-0

Many thanks for your help, this will help anyone who uses a Zyxel NAS and Spotify

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
