### ISSUE TITLE
Asterisk11 sounds path is incorrect

### ISSUE THREAD

**Issue by Suncatcher** [Entware/Entware-ng#727]
### Package: asterisk11-app-system, asterisk11-sounds

I see that [the problem with sounds path](http://www.linksysinfo.org/index.php?threads/toastman-entware-asterisk-config-issue.68378/#post-225475) is not yet resolved since 2013. Awful!
I installed latest asterisk11 package with sounds from the Entware repo, **asterisk.conf** config is default:

[directories]
astetcdir => /opt/etc/asterisk
astmoddir => /opt/lib/asterisk/modules
astvarlibdir => /opt/lib/asterisk
astdbdir => /opt/lib/asterisk
astkeydir => /opt/lib/asterisk
**astdatadir => /opt/lib/asterisk**
astagidir => /opt/lib/asterisk/agi-bin
astspooldir => /opt/var/spool/asterisk
astrundir => /opt/var/run/asterisk
astlogdir => /opt/var/log/asterisk
astsbindir => /opt/sbin

but it cannot find sounds anyway in /opt/lib/asterisk/sounds. Until I copied sounds to /opt/**var**/lib/asterisk/sounds it threw error.

### Platform:

AsusWRT-Merlin
Asus AC68-U

**Comment by zyxmon** [comment]
Please provide a PR for fix upstream or for entware. 
https://github.com/openwrt/telephony/blob/master/net/asterisk-11.x/Makefile#L339
https://github.com/openwrt/telephony/blob/master/net/asterisk-11.x/Makefile#L51
Or
https://github.com/Entware-ng/entware-telephony/blob/master/net/asterisk-11.x/Makefile#L333
https://github.com/Entware-ng/entware-telephony/blob/master/net/asterisk-11.x/Makefile#L51
Entware developers do not use asterisk and many other packages and cannot check the fix.

**Comment by Suncatcher** [comment]
I don't think that changing path in makefile will affect this bug. The path is listed correctly by Asterisk, but is treated incorrectly by it. The problem is elsewhere.

**Comment by zyxmon** [comment]
Probably the bug is asterisk configuration file or sources.

**Comment by Suncatcher** [comment]
I am not so fluent in Asterisk sources to pull smth myself.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
