### ISSUE TITLE
Package request: gkrellmd

### ISSUE THREAD

**Issue by DrCaFr** [Entware/Entware-ng#741]
### Package: <name>

I am using gkrellm on both, Linux and Windows since many years to monitor performance of local and remote systems.
"Killer features": gkrellm is the most versatile and cross-platform, but ressource efficient monitor tool I know.
The corresponding daemon (has no GUI) is called gkrellmd.
For details, see <http://gkrellm.srcbox.net/>.
Today, I upgraded my QNAP NAS from QTS 4.2 to 4.3.
QTS 4.3 does not longer support IPKG (which contained gkrellmd) and 32 bit. 
Recommended IPKG-replacement Entware-ng does not yet contain gkrellmd.
Since I desperately miss it, please add gkrellmd!

### Platform:

I am using QNAP TS-870 with x64 CPU

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
