### ISSUE TITLE
Package request: arp-scan

### ISSUE THREAD

**Issue by mikka2** [Entware/Entware-ng#745]
Package: arp-scan

https://github.com/royhills/arp-scan
http://www.nta-monitor.com/wiki/index.php/Arp-scan_Installation_Guide

This package can scan for devices in network which is great for network monitoring (enabled/disabled devices). Inside Entware repository there is only addrwatch package, which is logging all devices at the moment of joining/leaving network, but doesn't show current status.

According to documentation it only requires libpcap 0.9 or later, which is already available in Entware repository (current version is 1.8.1). 

Platform: Asus RT-AC68U (armv7)

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
