### ISSUE TITLE
Package request: mopidy

### ISSUE THREAD

**Issue by monosoul** [Entware/Entware-ng#754]
### Package: mopidy
It's MPD-like music server, **BUT** with plugins to play music from Google Play Music, Spotify etc.

### Platform:

MIPS (Asus RT-n66u), Merlin's firmware

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
