### ISSUE TITLE
Package request: Chromaprint

### ISSUE THREAD

**Issue by gravelld** [Entware/Entware-ng#758]
### Package: Chromaprint

Chromaprint is the open source client-side library for the [Acoustid](https://acoustid.org/) project. It implements a custom algorithm for extracting fingerprints from any audio source.

Chromaprint is used as the fingerprinting library by a number of software tools:

- beets
- bliss
- filebot

(Those off the top of my head).

Chromaprint has already been built and is used on Synology devices which use similar architectures. [It's also been added to Optware-ng](https://github.com/Optware/Optware-ng/commit/e2d6436fa0b7c22c9410c636cd9e2c9e70b8d3f4).

### Platform:
![image](https://user-images.githubusercontent.com/873704/29931559-857c6ba2-8e69-11e7-8ca9-9310cb850f9f.png)

Seriously, it would make sense to prioritise the most used. Me personally, for my testing, I have a x86_64 device.

**Comment by gravelld** [comment]
I've had a _bit_ of a go at doing this. I can get an fpcalc executable to compile, but when run on the QNAP this gives:
```
fpcalc: error while loading shared libraries: libavformat-ffmpeg.so.56: cannot open shared object file: No such file or directory
```
I think this is trying to use the `libavformat-ffmpeg.so.56` lib that's installed on the build machine. Somehow I need to tell it to use the QNAP's ffmpeg, I think.

Code so far is:

```
include $(TOPDIR)/rules.mk
include $(INCLUDE_DIR)/kernel.mk

PKG_NAME:=chromaprint
PKG_VERSION:=1.4.2
PKG_RELEASE:=1

PKG_BUILD_DIR:=$(BUILD_DIR)/chromaprint-$(PKG_VERSION)
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://github.com/acoustid/chromaprint/releases/download/v$(PKG_VERSION)
PKG_HASH:=989609a7e841dd75b34ee793bd1d049ce99a8f0d444b3cea39d57c3e5d26b4d4

PKG_INSTALL:=1

include $(INCLUDE_DIR)/package.mk

define Package/chromaprint
  TITLE:=Chromaprint
  URL:=https://acoustid.org/
  DEPENDS:= +ffmpeg
endef

define Package/chromaprint/description
 Chromaprint is an audio fingerprint library developed for the AcoustID project.
endef

define Package/chromaprint/install
#	For some reason something's required here for the build to do anything!
endef

define Build/Configure
	cd $(PKG_BUILD_DIR); \
		cmake \
			$(CMAKE_CONFIGURE_OPTS) \
			-DCMAKE_BUILD_TYPE=Release \
			-DBUILD_TOOLS=ON \
			-DFFMPEG_ROOT=/mnt/ext/opt/medialibrary/lib/ \
			-DFFT_LIB=avfft
endef

define Build/Compile
	cd $(PKG_BUILD_DIR); \
		$(MAKE) 
endef

$(eval $(call BuildPackage,chromaprint))
```

**Comment by rednoah** [comment]
+1

Wouldn't the binaries available for the various Synology platforms also work on QNAP devices out of the box?

**Comment by gravelld** [comment]
So long as the shared libraries are consistent... probably. An avenue worth trying.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
