### ISSUE TITLE
Package request: Radicale: htpasswd encryption method 'bcrypt' requires the passlib module with bcrypt support

### ISSUE THREAD

**Issue by jemail99** [Entware/Entware-ng#759]
### Package: Radicale
See; http://radicale.org/

I can install Python3 and Radicale, On execution of the radicale server I get:
[400ee110] ERROR: An exception occurred during server startup: The htpasswd encryption method 'bcrypt' requires the passlib module with bcrypt support. 

I require password encryption support. From  my own research-
When I try python3 -m pip install passlib[bcrypt]
I error with:
Running setup.py install for cffi ... error
    Complete output from command /opt/bin/python3 -u -c "import setuptools, tokenize;__file__='/opt/tmp/pip-build-vfghwyy1/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /opt/tmp/pip-chvouis0-record/install-record.txt --single-version-externally-managed --compile:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
   ...
arm-openwrt-linux-gnueabi-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -pipe -march=armv7-a -mtune=cortex-a9 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=soft -O2 -pipe -march=armv7-a -mtune=cortex-a9 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=soft -DNDEBUG -fno-inline -O2 -pipe -march=armv7-a -mtune=cortex-a9 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=soft -DNDEBUG -fno-inline -I/media/ware4/Entware-ng.2017.05/staging_dir/target-arm_cortex-a9_glibc-2.23_eabi/opt/include -I/media/ware4/Entware-ng.2017.05/staging_dir/target-arm_cortex-a9_glibc-2.23_eabi/include -I/media/ware4/Entware-ng.2017.05/staging_dir/toolchain-arm_cortex-a9_gcc-6.3.0_glibc-2.23_eabi/usr/include -I/media/ware4/Entware-ng.2017.05/staging_dir/toolchain-arm_cortex-a9_gcc-6.3.0_glibc-2.23_eabi/include -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/opt/include/python3.6 -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.6/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory

I have installed the libffi package and it is in /opt/lib.
Also I think this is problematic as those locations don't exist:
-I/usr/include/ffi -I/usr/include/libffi
but I have no idea how to fix this.
Some research suggests I need libffi-devel package?

Maybe a package guru could create a complete Radicale package with RadicaleInfCloud included?

### Platform:
Asus RTAC68U Shibby Tomato Firmware

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
