### ISSUE TITLE
Package request: ypserv

### ISSUE THREAD

**Issue by sfloess** [Entware/Entware-ng#761]
### Package: ypserv

For existing package:

- expected behavior: NIS server
- actual behavior: ...

For new package to be added: ypserv

- make sure there's no similar package already added,
- describe killer features of new package,
- make sure it's open source and not abandoned (at least for last 5 years or so),
- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

### Platform: Buffalo WZR-1750DHP

- please, tell us what feed and\or devices are you using.
- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
