### ISSUE TITLE
Package request: ebtables

### ISSUE THREAD

**Issue by uihdff** [Entware/Entware-ng#762]
### Package: ebtables 2.0.10-4

The ebtables program is a filtering tool for a Linux-based bridging firewall. It enables transparent filtering of network traffic passing through a Linux bridge. The filtering possibilities are limited to link layer filtering and some basic filtering on higher network layers. Advanced logging, MAC DNAT/SNAT and brouter facilities are also included. 

The source code is located here:

`ftp://ftp.netfilter.org/pub/ebtables/ebtables-v2.0.10-4.tar.gz`

### Platform: Asuswrt-Merlin 380.68 using kernel 2.6.36.4brcmarm
###Hardware: Asus RT-AC88U

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
