### ISSUE TITLE
Package request: ethereum-clients (Parity-1.7.0 would be really appreciated)

### ISSUE THREAD

**Issue by SephirothFFKH** [Entware/Entware-ng#764]
### Package: ethereum-clients (Parity-1.7.0)

- With the Ethereum altcoin becoming more popular by the day it is critical that more seed are created for the blockchain. I would like to sync and seed a full copy of the entire blockchain of 274.50 GB (as of today). It is not feasible for me to run and dedicate a computer for this task and I would like to use a Entware-ng application to do this task.

- While there are many actively developed open-source implementation listed in the etherdocs (http://ethdocs.org/en/latest/ethereum-clients/choosing-a-client.html) including the official geth client (https://github.com/ethereum/go-ethereum/releases), the most feature rich and fastest is, in my opinion, Parity-1.7.0 furthermore, it is the only one that has a precompiled version for ARMv7 Linux. The source code to Parity is availale here: https://github.com/paritytech/parity/releases Do note that I do not need the wallet management feature provided by Parity but only the blockchain synchronization client. 

Thank you very much

### Platform:

- RT-AC68U with ASUSWRT-Merlin 380.68_0

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
