### ISSUE TITLE
Bug: busybox 'tr' command broken

### ISSUE THREAD

**Issue by sbokor** [Entware/Entware-ng#769]
Hello,
I would like to report a bug in the 'tr' command of the latest busybox,

Package:
busybox_1.25.1-2_x86-64.ipk

Issue:
The "class" option for the 'tr' command doesn't behave as expected.

Example:
1. Raw input:
[~] # uname -s
Linux

2. Using the OS default busybox (1.24). Result is correct:
[~] # uname -s | /bin/tr [:upper:] [:lower:]    
linux

3. Using busybox_1.25.1-2_x86-64. Result is incorrect/mangled:
[~] # uname -s | /opt/bin/tr [:upper:] [:lower:]
Linlx

System:
Hardware = QNAP NAS. OS = QTS 4.3.3.0299.
Entware install package = Entware-ng_0.97.qpkg 

Stefan

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
