### ISSUE TITLE
Package update request: esniper

### ISSUE THREAD

**Issue by AnarkiQ3** [Entware/Entware-ng#779]
Version 2.32 is not working anymore, 2.33 was released to fix this. Also [here](https://pastebin.com/pq3DDmQV)'s a patch to the latest CVS version, which fixes some bugs, like segmentation fault

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
