### ISSUE TITLE
Package update request: inadyn

### ISSUE THREAD

**Issue by BrainInSight** [Entware/Entware-ng#781]
### Package: inadyn

Please update to v.2.2 (Currently 2.2-rc1). There is a problem with URL encoding in this versions, which prevent inadyn for working with my DynDNS provider. This issue (https://github.com/troglobit/inadyn/issues/152) is solved in the final v.2.2 release

### Platform:

-QNAP NAS

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
