### ISSUE TITLE
Package request: p7zip-zstd

### ISSUE THREAD

**Issue by pasha-zzz** [Entware/Entware-ng#800]
### Package: p7zip-zstd
https://github.com/tehmul/p7zip-zstd
p7zip with ZStandard support. Also can unpack LZip.

ASUS N18U, ARM7

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
