### ISSUE TITLE
Package request: lzip

### ISSUE THREAD

**Issue by pasha-zzz** [Entware/Entware-ng#801]
### Package: lzip
http://www.nongnu.org/lzip/lzip.html
Lzip is a lossless data compressor with a user interface similar to the one of gzip or bzip2.

ASUS N18U, ARM7

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
