### ISSUE TITLE
Package request: frp

### ISSUE THREAD

**Issue by Blaskyy** [Entware/Entware-ng#802]
### Package: frp

https://github.com/fatedier/frp

frp is a fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet. Now, it supports tcp, udp, http and https protocol when requests can be forwarded by domains to backward web services.

### Platform:

RT-AC66U_B1, ARMv7

**Comment by jingwanguo** [comment]
have you tried cross compile with "GOOS=linux GOARCH=arm GOARM=5 go build ..." ?

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
