### ISSUE TITLE
Pacakge request: atop

### ISSUE THREAD

**Issue by afunix** [Entware/Entware-ng#806]
Package: atop
Home: https://www.atoptool.nl/
License: GPL
Latest release: Sep-30 2017
Killer features: monitors CPU (including freq, etc), load average, mem&swap, disk io (LVM, MD, raw block devices), network io in a single screen
Platform: Synology DSM x86-64

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
