### ISSUE TITLE
Pacakge request: update Tvheadend

### ISSUE THREAD

**Issue by cuadedanh** [Entware/Entware-ng#810]
### Package: Tvheadend 
For existing package:
 the current is 4.0. pls update to latest version 4.2 with some new feature pls. Thank

- expected behavior: ...
- actual behavior: ...

For new package to be added:

- make sure there's no similar package already added,
- describe killer features of new package,
- make sure it's open source and not abandoned (at least for last 5 years or so),
- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

### Platform:

- please, tell us what feed and\or devices are you using.
- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

**Comment by VanilleGrobi** [comment]
I'd second the request

**Comment by ryzhovau** [comment]
4.2 consumes 40% more RAM, also, can't say it's compact, compared with 4.0.

https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
