### ISSUE TITLE
Pacakge request: <miredo>

### ISSUE THREAD

**Issue by chendaihang** [Entware/Entware-ng#815]
### Pacakge request: <miredo>
link：https://www.remlab.net/miredo
for mipsel
‘’6in4‘’ need  public network IP(we call it ‘’公网ip‘’)，but  I dont have。
so I wish it，thinks a lot if I can get it。

**Comment by chendaihang** [comment]
@ryzhovau

**Comment by Lichtenshtein** [comment]
Is it possible to break through provider's NAT with 6in4 as Teredo does on windows? I have "grey" ip and tunnel brokers just don't work for me. I thought miredo will help.

[https://github.com/fgp/miredo](url)
Platform Xiaomi-Mi Mini/Asus RT-N56U, mipsel

**Comment by nickonline2005** [comment]
@ryzhovau, Currently I am using 6to4 or 6in4 tunnel, but both of them are unstable (some time unreachable) or have a high latency. For now, the teredo tunnel is the most reliable and fast service that I can use. So for as I know, miredo is the only choice to use the toredo tunnel on linux platform, so I tried to compile the miredo package myself, but I failed. So, please, add the package for armv7 and mipsel platform, thanks a lot.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
