### ISSUE TITLE
Package request: hostapd

### ISSUE THREAD

**Issue by MrDini123** [Entware/Entware-ng#818]
https://wireless.wiki.kernel.org/en/users/documentation/hostapd

I wanted to set up radius accounting on my mipsel based router with Tomato and Entware-ng. But there is no hostapd package in the repositories.

Can you please compile a hostapd package?

Thanks.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
