### ISSUE TITLE
Package request : museek+

### ISSUE THREAD

**Issue by vlotho** [Entware/Entware-ng#820]
hi,

### Package: museek+

Museek+ is a GPL licensed file-sharing application for the ​Soulseek peer-to-peer network.

http://www.museek-plus.org

Soulseek is an ad-free, spyware free, just plain free file sharing network for Windows, Mac and Linux. Our rooms, search engine and search correlation system make it easy for you to find people with similar interests, and make new discoveries!   

http://www.slsknet.org/news/

### Platform:

i use the adm asustor platform (x86_64)  AS3104T

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
