### ISSUE TITLE
Package request: reredirect

### ISSUE THREAD

**Issue by tenwx** [Entware/Entware-ng#824]
Package: reredirect
For existing package:
none
expected behavior: A tool to dynamically redirect outputs of a running program. (Not support mips platform)
The source code is located here:
https://github.com/jerome-pouiller/reredirect.git
Platform:
Asus RT-AC68U

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
