### ISSUE TITLE
Package-Request: dump/restore

### ISSUE THREAD

**Issue by Ingo0876** [Entware/Entware-ng#825]
### Package: dump
For new package to be added:
- dump and restore for ext2/3/4 filesystems
http://dump.sourceforge.net/

Key features:
- compatbility to existing backups

### Platform: x86_64

Device used:
QNAP TS-251A-4G

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
