### ISSUE TITLE
Package-Request: hardlink

### ISSUE THREAD

**Issue by herrold** [Entware/Entware-ng#826]
### Package: hardlink

For new package to be added:

- make sure there's no similar package already added,

   none seen

- describe killer features of new package,

    hardlink is used to create a tree of hard links.  They maintainer thinks it is useful for Linux kernel developers, but I use it heavily for mirroring of Source packages generally

- make sure it's open source and not abandoned (at least for last 5 years or so),

    upstream maintainer page: https://pagure.io/hardlink

    upstream GIT: https://pagure.io/hardlink.git

    The package in in active maintenance, last git commit Aug 19 2017 per Changelog

- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

    N/A  -- it is C code and a man page

### Platform:

- please, tell us what feed and\or devices are you using.

    http://pkg.entware.net/binaries/armv7/Packages.gz

- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

    I follow GitHub each weekday and try to clear issues promptly

**Comment by herrold** [comment]
I also have an older QNAP unit, and would use it from the archive at:

    http://pkg.entware.net/binaries/armv5/Packages.gz

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
