### ISSUE TITLE
Package request: airprint

### ISSUE THREAD

**Issue by dchen4649** [Entware/Entware-ng#834]
### Package: airprint package to be installed on USB flash drive for OpenWRT / DD-WRT.

For existing package:

- expected behavior: ...
- actual behavior: ...

For new package to be added:

- make sure there's no similar package already added,
- describe killer features of new package,
- make sure it's open source and not abandoned (at least for last 5 years or so),
- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

### Platform:

- please, tell us what feed and\or devices are you using.
- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
