### ISSUE TITLE
Package Request: Plexdrive

### ISSUE THREAD

**Issue by shadowsbane0** [Entware/Entware-ng#847]
### Package: <Plexdrive>

For existing package:  
- expected behavior: ... 
- actual behavior: ... 

For new package to be added:

- make sure there's no similar package already added,
- describe killer features of new package,

Provide a Google Drive mount point for Plex Media Servers to use. Plexdrive provides a read-only cache for the Google Drive Cloud Storage. Most embedded devices with a Plex Media Server installed will only look for media on attached USB or a locally shared network source. Plexdrive adds Google Drive indexing capability.

Current attempts to install the Arm7 Plexdrive project onto an Entware enabled Router (Netgear R9000 with Voxel FW) result in the /Overlay and / FS filling up during the cache build task prematurely halting the process. My cache right now sits at around 355MB on the Ubuntu Server I am trying to migrate from. I have yet to figure out how to write it to the drive outside of the /Overlay FS and directly to the USB drive where there is plenty of space for the cache.bolt file to build.

I feel there is something not right with the Entware build because /Opt doesn't have the correct filesize to match the USB HDD. It has the same size as the on-board system memory.

- make sure it's open source and not abandoned (at least for last 5 years or so),
- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

### Platform: A7

Project Feed: https://github.com/dweidenfeld/plexdrive  
My Device: Netgear R9000 w/Voxel FW 1.47HF-HW w/500GB USB 3.0 HDD w/Voxel Optimized Entware

- please, tell us what feed and\or devices are you using.
- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
