### ISSUE TITLE
Package Request: gphoto2, libgphoto2

### ISSUE THREAD

**Issue by h4de5** [Entware/Entware-ng#848]
### Package: gphoto2

For new package to be added:
sudo apt-get install gphoto2

more information
http://gphoto.org/
https://github.com/gphoto/gphoto2
https://github.com/gphoto/libgphoto2
https://sourceforge.net/projects/gphoto/files/gphoto/

- with this package it's possible to run a sync server for WiFi enabled cameras on the NAS
- so instead of having to run a bloated camera suite (like sony's) to sync photos via an adhoc WiFi, you could run a script on your NAS and move the files directly (e.g.: https://github.com/falk0069/sony-pm-alt)
- gphoto was on optware but was never updated there, thats why i switched.

### Platform:
- Synology, DS1512+, x86_64

**Comment by h4de5** [comment]
gphoto2 and libgphoto2 just got updated on optware-ng - if this helps:
https://github.com/Optware/Optware-ng/pull/255

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
