### ISSUE TITLE
libhidapi-hidraw

### ISSUE THREAD

**Issue by ikuria** [Entware/Entware-ng#854]
### Package: libhidapi-hidraw

pls add libhidapi-hidraw as package because that is the goal to get the flirc-dongle to work (i hope)

### Platform:
- QNAP TS-228

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
