### ISSUE TITLE
Update rclone to v1.3.9

### ISSUE THREAD

**Issue by cbruegg** [Entware/Entware-ng#862]
Currently, rclone in entware is at v1.3.7, while the latest version is already v1.3.9, containing e.g. important performance improvements. See [changelog](https://rclone.org/changelog/).

Thanks in advance!

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
