### ISSUE TITLE
Package request: colrm/util-linux

### ISSUE THREAD

**Issue by Alacard** [Entware/Entware-ng#863]
For new package to be added:

- **describe killer features of new package**,
The colrm command removes selected columns from a file. Input is taken from standard input. Output is sent to standard output.

If called with one parameter, the columns of each line are removed starting with the specified column. If called with two parameters, the columns from the first column to the last column are removed.

### Platform:
Qnap 86_64

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
