### ISSUE TITLE
Package update request: softethervpn

### ISSUE THREAD

**Issue by hidekichi0917** [Entware/Entware-ng#867]
Could you please update softethervpn to version 4.25 Build 9656?
This version addresses vulnerabilities, memory leaks and bug fixes over older versions.

http://www.softether.org/5-download/history

Platform : armv7

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
