### ISSUE TITLE
New Package Request: ecryptfs-utils

### ISSUE THREAD

**Issue by azavoloka** [Entware/Entware-ng#871]
### New Package Request: ecryptfs-utils
Ability to use encrypted folders is a high plus (must have for me).
Source: http://ecryptfs.org/

Alternative: cryfs, available in opkg, but currently beta (huge disadvantage).

### Platform:
Linksys WRT3200ACM, arm_cortex-a9+vfpv3

**Comment by zyxmon** [comment]
encryptfs is primarly a kernel space solution, contact your firmware manyfacurer for kernel drivers.
Userspace encryptfs version was not updated for 7 years.
I would prefer cryfs in this case.
Please next time use Entware-3x issues page, in case you use it.
I am keeping issue open for more similar requests for some time.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
