### ISSUE TITLE
getssl script for "lets-encrypt" gnu ca-cert requires updated "curl"

### ISSUE THREAD

**Issue by stevebovy** [Entware/Entware-ng#873]
### Package: curl

**RT-AC66U_B1:/jffs/getssl# ./getssl**
getssl:  **curl needs updating, your version does not support SNI (multiple SSL domains on a single IP)**

### Platform: RT-AC66U

Linux RT-AC66U_B1 2.6.36.4brcmarm #1 SMP PREEMPT Wed Jan 31 17:32:52 CST 2018 armv7l GNU/Linux

**# ./getssl --help**
getssl ver. 2.10
**Obtain SSL certificates from the letsencrypt.org ACME server**

Usage: getssl [-h|--help] [-d|--debug] [-c|--create] [-f|--force] [-a|--all] [-q|--quiet] [-Q|--mute] [-u|--upgrade] [-k|--keep #] [-U|--nocheck] [-r|--revoke cert key] [-w working_dir] domain

Options:
  -a, --all          Check all certificates
  -d, --debug        Outputs debug information
  -c, --create       Create default config files
  -f, --force        Force renewal of cert (overrides expiry checks)
  -h, --help         Display this help message and exit
  -q, --quiet        Quiet mode (only outputs on error, success of new cert, or getssl was upgraded)
  -Q, --mute         Like -q, but mutes notification about successful upgrade
  -r, --revoke   "cert" "key" [CA_server] Revoke a certificate (the cert and key are required)
  -u, --upgrade      Upgrade getssl if a more recent version is available
  -k, --keep     "#" Maximum amount of old getssl versions to keep when upgrading
  -U, --nocheck      Do not check if a more recent version is available
  -w working_dir "Working directory"

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
