### ISSUE TITLE
transmission  inconsistent with default curl

### ISSUE THREAD

**Issue by cfpp2p** [Entware/Entware-ng#874]
For existing packages:

- transmission
- transmission-cfp

expected behavior: ... http announce and port check work with openwrt default curl --without-zlib
actual behavior: ... http announce and port check work inconsistently

https://github.com/openwrt/packages/pull/4807#issuecomment-362147814
https://github.com/openwrt/packages/issues/5459#issuecomment-362148603

latest revision at openwrt: **fixed** for transmission 2.93

latest revision transmission-cfp **fixed**
PKG_REV:=d0c97a058d1d5f81028d3b91f209d36582cfc756
by https://github.com/cfpp2p/transmission/commit/db9726daf8ab75196d7b841be445486c9feb549a

**Comment by ryzhovau** [comment]
Got it!
https://github.com/Entware-ng/merge
