### ISSUE TITLE
Package request: siproxd

### ISSUE THREAD

**Issue by kbaryshnikov** [Entware/Entware-ng#878]
Package: siproxd
Home page: http://siproxd.sourceforge.net/
License: GPLv2
Latest release: 0.8.3dev 17-Jan-2018
Killer features: SIP proxy/masquerading
Platform: ASUS RT-AC68U (armv7l)

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
