### ISSUE TITLE
Package update request : mpd-full

### ISSUE THREAD

**Issue by funnuraba21** [Entware/Entware-ng#880]
### Package: <mpd-full>

For existing package:

- expected behavior: using httpd output to create a flac or ogg stream.
- actual behavior: only wave encoder is available for httpd output

For new feature package to be added:

- include flac and ogg encoder for the httpd output

### Platform:

- Synology DS115J, ARMv7 (Armada 370)

Thanks

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
