### ISSUE TITLE
[REQ] 7z (in addition to 7za)

### ISSUE THREAD

**Issue by pasha-zzz** [Entware/Entware-ng#883]
### Package: p7zip

Please add 7z + 7z.so + Codecs\Rar.so from p7zip... At least usual, non-zstd versions.
Thanks.

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
