### ISSUE TITLE
Missing nut-driver-blazer_ser

### ISSUE THREAD

**Issue by mikeS7** [Entware/Entware-ng#891]
##  opkg info nut-driver-blazer_ser
Package: nut-driver-blazer_ser
Version: 2.7.4-4
Depends: libc, libssp, nut
Status: install user not-installed
Architecture: mipselsf
Installed-Time: 1494437167

Actually there are no package in repository
## opkg install nut-driver-blazer_ser
Installing nut-driver-blazer_ser (2.7.4-4) to root...
Collected errors:
 * opkg_download_pkg: Package nut-driver-blazer_ser is not available from any configured src.
 * opkg_install_pkg: Failed to download nut-driver-blazer_ser. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package nut-driver-blazer_ser.

Could you please build a new one?

Спасибо

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/merge

Please, add new issue [here](https://github.com/Entware/Entware/issues) if you still interested.

Sorry for inconvenience.
